In [1]:
import pandas as pd


##Reading the required dataset


In [2]:
dataset = pd.read_csv("/content/winequality-red.csv")


In [3]:
dataset.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [4]:
dataset


fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

##Preparing Data for Classification

The quality of the wine is split into 'Good' and 'Bad' based on the rating it has been given

In [5]:
quality = dataset["quality"].values
category = []
for num in quality:
    if num<=6:
        category.append("Bad")
    else :
        category.append("Good")

In [6]:
category = pd.DataFrame(data=category, columns=["Quality_class"])

In [7]:
dataset1 = pd.concat([dataset,category],axis=1)
dataset1.drop(columns="quality",axis=1,inplace=True)

In [8]:
dataset1

fixed acidity  volatile acidity  ...  alcohol  Quality_class
0               7.4             0.700  ...      9.4            Bad
1               7.8             0.880  ...      9.8            Bad
2               7.8             0.760  ...      9.8            Bad
3              11.2             0.280  ...      9.8            Bad
4               7.4             0.700  ...      9.4            Bad
...             ...               ...  ...      ...            ...
1594            6.2             0.600  ...     10.5            Bad
1595            5.9             0.550  ...     11.2            Bad
1596            6.3             0.510  ...     11.0            Bad
1597            5.9             0.645  ...     10.2            Bad
1598            6.0             0.310  ...     11.0            Bad

[1599 rows x 12 columns]

In [9]:
X= dataset1.iloc[:,:-1].values
y=dataset1.iloc[:,-1].values

In [10]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
y= le.fit_transform(y)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

##Importing and Applying Different Classification Algorithms

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [14]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel= 'rbf')

In [15]:
l_cla.fit(X_train, y_train)
k_cla.fit(X_train, y_train)
d_cla.fit(X_train, y_train)
r_cla.fit(X_train, y_train)
s_cla.fit(X_train, y_train)
ks_cla.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [16]:
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [17]:
l_pred = l_cla.predict(X_test)
k_pred = k_cla.predict(X_test)
d_pred = d_cla.predict(X_test)
r_pred = r_cla.predict(X_test)
s_pred = s_cla.predict(X_test)
ks_pred = ks_cla.predict(X_test)

Confusion Matrices For each Algorithms

In [18]:
from sklearn.metrics import confusion_matrix

In [19]:
l_c = confusion_matrix(y_test, l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)

In [20]:
l_c

array([[277,  13],
       [ 18,  12]])

In [21]:
k_c

array([[276,  14],
       [ 13,  17]])

In [22]:

d_c

array([[269,  21],
       [  8,  22]])

In [23]:

r_c

array([[278,  12],
       [ 13,  17]])

In [24]:
s_c

array([[290,   0],
       [ 30,   0]])

In [25]:
ks_c

array([[285,   5],
       [ 21,   9]])

In [26]:
from sklearn.metrics import accuracy_score

In [27]:
l_a = accuracy_score(y_test, l_pred)
k_a = accuracy_score(y_test, k_pred)
d_a = accuracy_score(y_test, d_pred)
r_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

In [28]:

print('Logistic Regression: ' + str(l_a) + '\nKNN : ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(l_a))

Logistic Regression: 0.903125
KNN : 0.915625
Decision Tree: 0.909375
Random Forest: 0.921875
Linear SVC: 0.90625
Kernel SVC: 0.903125


##Preparing Data for Regression

In [29]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [30]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2)

In [31]:
from sklearn.preprocessing import StandardScaler
t_train = y_train.reshape(len(y_train),1)
t_test = y_test.reshape(len(y_test),1)
X_sc = StandardScaler()
y_sc = StandardScaler()

In [32]:
X_std_train = X_sc.fit_transform(X_train)
y_std_train = y_sc.fit_transform(t_train)

In [33]:
X_std_test = X_sc.transform(X_test)
y_std_test = y_sc.transform(t_test)

##Importing and Applying Different Regression Algorithms

In [34]:
from sklearn.linear_model import LinearRegression 
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

In [35]:
m_reg=LinearRegression()
p_reg=LinearRegression()
d_reg=DecisionTreeRegressor()
r_reg=RandomForestRegressor()
s_reg=SVR()

In [36]:
X_poly = PolynomialFeatures(degree=2)
X_poly = X_poly.fit_transform(X_train)

In [37]:
m_reg.fit(X_train,y_train)
p_reg.fit(X_poly,y_train)
r_reg.fit(X_train,y_train)
d_reg.fit(X_train,y_train)
s_reg.fit(X_std_train,y_std_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [38]:
temp = PolynomialFeatures(degree =2)
temp = temp.fit_transform(X_test)

In [39]:
m_pred=m_reg.predict(X_test)
p_pred=p_reg.predict(temp)
r_pred=r_reg.predict(X_test)
d_pred=d_reg.predict(X_test)
s_pred=s_reg.predict(X_std_test)

In [40]:
from sklearn.metrics import r2_score

In [41]:
m= r2_score(y_test,m_pred)
p= r2_score(y_test,p_pred)
r= r2_score(y_test,r_pred)
d= r2_score(y_test,d_pred)
s= r2_score(y_std_test,s_pred)

In [42]:
print('Linear Regression: ' + str(m) + '\nPolynomial Regression. : ' + str(p) + '\nDecision Tree: ' + str(d) + '\nRandom Forest: ' + str(r) + '\nSupport Vector Regression SVC: ' + str(s) )

Linear Regression: 0.32834226872786854
Polynomial Regression. : 0.24156971454665843
Decision Tree: -0.09515859766277135
Random Forest: 0.4813563939899833
Support Vector Regression SVC: 0.38178491105703116


##Conclusion
Hence in conclusion, for both Classification and Regression, Random Forest Algorithm is giving the best result